# generated by datamodel-codegen:
#   filename:  https://raw.githubusercontent.com/EOSC-Data-Commons/metadata-warehouse/refs/heads/main/src/config/schema.json
#   timestamp: 2026-03-09T16:23:43+00:00

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field, RootModel


class Title(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    title: str
    lang: Annotated[str | None, Field(pattern='^[a-z]{2}$')] = None
    titleType: str | None = None


class Subject(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    subject: str
    lang: Annotated[str | None, Field(pattern='^[a-z]{2}$')] = None
    subjectScheme: str | None = None
    schemaUri: str | None = None
    valueUri: str | None = None
    classificationCode: str | None = None


class Creator(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    creatorName: str
    nameType: str | None = None
    nameIdentifierScheme: str | None = None
    nameIdentifier: str | None = None
    givenName: str | None = None
    familyName: str | None = None


class Description(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    description: str
    descriptionType: str
    lang: Annotated[str | None, Field(pattern='^[a-z]{2}$')] = None


class Date(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    date: Annotated[str, Field(pattern='^[0-9]{4}-[0-9]{2}-[0-9]{2}$')]
    dateType: str


class Types(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    resourceType: str | None = None
    resourceTypeGeneral: str


class DataciteRecord1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str
    doi: str
    url: str | None = None
    titles: list[Title]
    subjects: list[Subject] | None = None
    creators: list[Creator]
    publicationYear: Annotated[str | None, Field(pattern='^[0-9]{4}$')] = None
    descriptions: list[Description] | None = None
    dates: list[Date] | None = None
    types: Types


class DataciteRecord2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str
    doi: str | None = None
    url: str
    titles: list[Title]
    subjects: list[Subject] | None = None
    creators: list[Creator]
    publicationYear: Annotated[str | None, Field(pattern='^[0-9]{4}$')] = None
    descriptions: list[Description] | None = None
    dates: list[Date] | None = None
    types: Types


class DataciteRecord(RootModel[DataciteRecord1 | DataciteRecord2]):
    root: DataciteRecord1 | DataciteRecord2
